### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by PowerPress** [felipedau/nymphemeral#28]
Please enable HTTPS on http://nym.now.im/nymserver/ to ensure that the user is getting the correct private key and is not being tampered with.

**Comment by felipedau** [comment]
Unfortunately, https://nym.now.im has only a self-signed cert and it is unlikely it will get one issued by some known CA. However, 2b4eef98cbc0ba4544ac055a69f79f76234ffa94 introduced changes to include the key in the source and I hope that it solves part of the problem.
