### ISSUE TITLE
Creating nym using mixmaster option

### ISSUE THREAD

**Issue by PowerPress** [felipedau/nymphemeral#30]
Terminal showed the following:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 136, in <lambda>
    entry_passphrase_login.get()))
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 166, in start_session
    self.start_session(address, passphrase, True)
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 168, in start_session
    self.gui.start_session(creating_nym)
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 51, in start_session
    self.window_main = MainWindow(self, self.client, creating_nym)
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 343, in __init__
    text='Mix chain: ' + self.client.chain)
TypeError: cannot concatenate 'str' and 'NoneType' objects
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 421, in <lambda>
    self.entry_duration_create.get()))
  File "/usr/local/lib/python2.7/dist-packages/nymphemeral/gui.py", line 460, in create
    self.gui.window_main.set_creation_interface(False)
AttributeError: 'NoneType' object has no attribute 'set_creation_interface'

But software shows following in gui: The following message was successfully sent to config@nym.now.im

Appears my gui is no longer responding and cannot switch tabs.

This is on Whonix Workstation

**Comment by felipedau** [comment]
Thanks for the report, @PowerPress!

> Appears my gui is no longer responding and cannot switch tabs.

This issue you are having seems to be related from the trace and it looks like an easy bug to fix. I'm sorry for the inconvenience.

> But software shows following in gui: The following message was successfully sent to config@nym.now.im

A report made in #19 shows that nymphemeral is not detecting when the transmission fails and you might get a confirmation like that. It doesn't seem that the error you got from the trace is related to this issue. I hope I can find a way to solve it, but it's not so simple.

**Comment by felipedau** [comment]
Hi @PowerPress,

The error from the trace you got should be fixed with 064476a2a0906e2267a7497508973cb7a67356e7.

After the fix, the GUI should respond properly and your message should be sent. If you believe that the transmissions failed but the confirmation was displayed anyway, please reply to #19 with any additional information that can help me fix that.

Thanks!

**Comment by PowerPress** [comment]
Dumb question but how do I apply this fix?

Do I need to uninstall the app and is so what command would I use?

Thanks

**Comment by felipedau** [comment]
> Dumb question but how do I apply this fix? Do I need to uninstall the app and is so what command would I use?

After I sent the message, I edited to add more information (with the command to update). As I see that you are using email to reply, you probably didn't get the new information. Here is how to do it:

If you installed nymphemeral with **pip**, you can update it with `sudo pip install --upgrade nymphemeral`. Then you can check the current version with `pip list | grep nymphemeral`. Let me know if it works.

I should add an update section to the docs.

**Comment by PowerPress** [comment]
Ok that worked. I then went to
https://nymphemeral.readthedocs.org/en/latest/install/connections-whonix.html#connections-whonix
Because I dont have a news added I did the following:

sudo apt-get install stunnel4

sudo curl https://raw.githubusercontent.com/felipedau/nymphemeral/master/connections/stunnel-whonix.conf
-o /etc/stunnel/stunnel.conf

/etc/default/stunnel4 added enable=1

sudo service stunnel4 start

But never received any messages.

Now I still cant find any news servers even if I close and reopen the app.

**Comment by felipedau** [comment]
> But never received any messages.
>
> Now I still cant find any news servers even if I close and reopen the app.

So at first it tried to find messages by loading a progress bar and now you only get an error message, right?

> /etc/default/stunnel4 added enable=1

Make sure that the option is `ENABLED=1`, otherwise it will not start automatically. That might be the reason it only worked once. You might want to run `sudo service stunnel4 start` again.

Can you check if stunnel is running with `sudo service stunnel4 status`? If it is then we need to check if you are able to connect to the news server calling `telnet localhost 119`. If it connects, you can type `quit` to close. 

If you're able to connect to the news server with *telnet*, then it might be a bug on nymphemeral.

**Comment by PowerPress** [comment]
# Change to one to enable stunnel automatic startup
ENABLED=1
FILES="/etc/stunnel/*.conf"
OPTIONS=""

executing the following:
user@host:/etc/stunnel$ sudo service stunnel4 start
user@host:/etc/stunnel$

Notice it does not return any information once that command is executed.

user@host:/etc/stunnel$ sudo service stunnel4 status
● stunnel4.service - LSB: Start or stop stunnel 4.x (SSL tunnel for network
daemons)
   Loaded: loaded (/etc/init.d/stunnel4)
   Active: active (exited) since Tue 2015-09-15 01:10:45 UTC; 21h ago

Sep 15 22:50:40 host systemd[1]: Started LSB: Start or stop stunnel 4.x
(SS...).
Warning: Journal has been rotated since unit was started. Log output is
incomplete or unavailable.
Hint: Some lines were ellipsized, use -l to show in full.

user@host:/etc/stunnel$ telnet localhost 119
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Comment by PowerPress** [comment]
Any ideas on what I can do next bud?

**Comment by felipedau** [comment]
> Any ideas on what I can do next bud?

Let's find out if for some reason the connection to the news server is being blocked. Try to connect without stunnel with `telnet news.mixmin.net 563`.

Then I'd like that you confirmed that you succesfully downloaded the `stunnel-whonix.conf` file and saved it at `/etc/stunnel/` as `stunnel.conf`. It is important that (to download messages) it must have the `nntps-client` section at the bottom:

```
[nntps-client]
client = yes
accept = 127.0.0.1:119
connect = news.mixmin.net:563
```

**Comment by PowerPress** [comment]
user@host:~$ telnet news.mixmin.net 563
Trying 188.40.76.149...
Connected to news.mixmin.net.
Escape character is '^]'.

Success

nano /etc/stunnel/stunnel.conf
; Example SSL server mode services

[nntps-client]
client = yes
accept = 127.0.0.1:119
connect = news.mixmin.net:563

[ssmtp-client]
protocol = smtp
client = yes
accept = 127.0.0.1:25
connect = 2.2.2.2:25

Appears success from above

**Comment by PowerPress** [comment]
Extra info trying to get this to work on Whonix

user@host:~$ cat /home/user/.Mix/mix.cfg
SMTPRELAY 1.1.1.1
SMTPRELAY 2.2.2.2

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## /home/user/.Mix/mix.cfg
## Do not add comments on top of the file,
## because mixmaster does not support that.

**Comment by felipedau** [comment]
> Appears success from above

Apparently the issue is stunnel. It seems to be correctly installed and configured. The only thing that I noticed is that the output from `service stunnel status` says it is `active (exited)`, but should be `running`, and I really don't know why.

> PowerPress commented 2 hours ago
> Extra info trying to get this to work on Whonix
> 
> user@host:~$ cat /home/user/.Mix/mix.cfg
> SMTPRELAY 1.1.1.1
> SMTPRELAY 2.2.2.2

Do not forget there is a [Mixmaster (Whonix)] section and the config you have there would not use stunnel to connect to the SMTP server. You should have `SMTPRELAY localhost` instead. However, that does not solve the issue, which is getting stunnel to work.

I've been very busy lately and I will try to create a Whonix installation again to find a solution, but can't promise you I will. I'll let you know if I get any progress and please keep me updated as well. **We must find a solution!**

[mixmaster (whonix)]: https://nymphemeral.readthedocs.org/en/latest/install/mixmaster-whonix.html#mixmaster-whonix

**Comment by PowerPress** [comment]
Sounds like a plan. Thank you

**Comment by PowerPress** [comment]
It appearsd just needed to run:

sudo service stunnel4 status
● stunnel4.service - LSB: Start or stop stunnel 4.x (SSL tunnel for network
daemons)
   Loaded: loaded (/etc/init.d/stunnel4)
   Active: active (running) since Sat 2015-09-19 03:43:48 UTC; 15s ago
  Process: 9758 ExecStop=/etc/init.d/stunnel4 stop (code=exited,
status=0/SUCCESS)
  Process: 9772 ExecStart=/etc/init.d/stunnel4 start (code=exited,
status=0/SUCCESS)
   CGroup: /system.slice/stunnel4.service
           └─9785 /usr/bin/stunnel4 /etc/stunnel/stunnel.conf

Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: stunnel 5.06 on
i586-pc-lin...rm
Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: Compiled/running with
OpenS...15
Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: Threading:PTHREAD
Sockets:P...AP
Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: Reading configuration from
...nf
Sep 19 03:43:48 host systemd[1]: Started LSB: Start or stop stunnel 4.x
(SS...).
Sep 19 03:43:48 host stunnel4[9772]: Starting SSL tunnels: [Started:
/etc/s...l.
Hint: Some lines were ellipsized, use -l to show in full.

Now how do I fix the Mix Chain Unknown @ the bottom is that due to chain
not being specified in /home/user/.Mix/mix.cfg? Also how would it know what
servers to chain specifically?

**Comment by PowerPress** [comment]
What happens if you don't specify a chain?

On Fri, Sep 18, 2015 at 10:49 PM, Jonathan Brown <jonbrownmasterit@gmail.com
> wrote:

> It appearsd just needed to run:
>
> sudo service stunnel4 status
> ● stunnel4.service - LSB: Start or stop stunnel 4.x (SSL tunnel for
> network daemons)
>    Loaded: loaded (/etc/init.d/stunnel4)
>    Active: active (running) since Sat 2015-09-19 03:43:48 UTC; 15s ago
>   Process: 9758 ExecStop=/etc/init.d/stunnel4 stop (code=exited,
> status=0/SUCCESS)
>   Process: 9772 ExecStart=/etc/init.d/stunnel4 start (code=exited,
> status=0/SUCCESS)
>    CGroup: /system.slice/stunnel4.service
>            └─9785 /usr/bin/stunnel4 /etc/stunnel/stunnel.conf
>
> Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: stunnel 5.06 on
> i586-pc-lin...rm
> Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: Compiled/running with
> OpenS...15
> Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: Threading:PTHREAD
> Sockets:P...AP
> Sep 19 03:43:48 host stunnel[9784]: LOG5[9784]: Reading configuration from
> ...nf
> Sep 19 03:43:48 host systemd[1]: Started LSB: Start or stop stunnel 4.x
> (SS...).
> Sep 19 03:43:48 host stunnel4[9772]: Starting SSL tunnels: [Started:
> /etc/s...l.
> Hint: Some lines were ellipsized, use -l to show in full.
>
> Now how do I fix the Mix Chain Unknown @ the bottom is that due to chain
> not being specified in /home/user/.Mix/mix.cfg? Also how would it know what
> servers to chain specifically?
>
> On Fri, Sep 18, 2015 at 8:04 AM, Jonathan Brown <

**Comment by felipedau** [comment]
> It appearsd just needed to run:

Great. So, what exactly did you run to fix  the issue?

> Now how do I fix the Mix Chain Unknown @ the bottom is that due to chain not being specified in /home/user/.Mix/mix.cfg? Also how would it know what servers to chain specifically?

Yeap, you're right, but that's not an error. It just means that nymphemeral doesn't know the chain that will be used because it's not specified in the file. That option is not mandatory, because Mixmaster has a default chain. I cannot say for sure, but I beleive it then uses 4 random mixes (`*,*,*,*`).

**Comment by PowerPress** [comment]
I just had to run the stunnel restart command. This got stunnel running "sudo
service stunnel4 restart"

**Comment by felipedau** [comment]
> I just had to run the stunnel restart command. This got stunnel running "sudo service stunnel4 restart"

I totally forgot about that one!

 Thanks for your feedback, @PowerPress.
