### ISSUE TITLE
Time/Date new messages

### ISSUE THREAD

**Issue by PowerPress** [felipedau/nymphemeral#31]
Would it be possible to include in the new received messages the time/date they were received?

**Comment by felipedau** [comment]
It is possible, but can you tell me why the user would want that?

**Comment by PowerPress** [comment]
Its working now I just didnt for the initial message I got when I created
the nym. Any emails received to that email does show the date/time
received. So we close this issue

**Comment by felipedau** [comment]
> Its working now I just didnt for the initial message I got when I created the nym. Any emails received to that email does show the date/time received. So we close this issue

Ohh, I see. I thought you wanted to know when they were sent and when they were downloaded.

Yeah, the creation confirmation does not have a `Date` header (it actually has no headers) :/
