### ISSUE TITLE
Display Nym Duration

### ISSUE THREAD

**Issue by PowerPress** [felipedau/nymphemeral#35]
Please display Nym Duration or amount of time left before the Nym self deletes. This would be very helpful if you forget that a Nym has expired and you will be expecting email. Otherwise you get Passphrase provided is incorrect.

**Comment by felipedau** [comment]
That's a great idea, @PowerPress!

Thank you for using nymphemeral, I hope you are having no problems with it :)

**Comment by felipedau** [comment]
I am closing this issue because the simpler part of it is handled by 740e71c615c4bfed203af88a409b0ad52841ed0e and I opened #36 to handle expired nyms, which is the the other (not so simple) part.

I hope the new feature is what you expect :)
